### ISSUE TITLE
the ability to copy and modify the text generated by GPT

### ISSUE THREAD

**Issue by MILKMILKKING** [micahke/obsidian-gpt3-notes#1]
First of all your plugin is great!
Could you add a feature: the ability to copy and modify the text generated by GPT.
Because there are times when the plugin doesn't seem to insert successfully into the document.

**Comment by KennyDenvers** [comment]
I agree, the plugin is great! Thank you very much for making it!

I don't know if this is also meant by this issue, but someetimes not all of the text that is generated by GPT-3 is shown, but instead it breaks off in mid-sentence.

**Comment by micahke** [comment]
@KennyDenvers this seems to be a limitation of the OpenAI API. Will take a look though
