### ISSUE TITLE
[Feature Request] Add a api_url options

### ISSUE THREAD

**Issue by makerjackie** [micahke/obsidian-gpt3-notes#17]
sometimes we need a different api_url rather than `https://api.openai.com`, for example azure openai server or though a proxy server. could you add this option?

![image](https://user-images.githubusercontent.com/18050469/227776124-a3074bdf-0330-4257-b5b5-ad7140010503.png)

**Comment by Pukimaa** [comment]
I actually wanted this as well...I can code so I'll try to make a PR :)
