### ISSUE TITLE
Chat completion head lost in preview

### ISSUE THREAD

**Issue by rizerphe** [micahke/obsidian-gpt3-notes#18]
When generating a chat completion (`gpt-3.5-turbo`), the first few characters - potentially the first token - are not displayed in the preview window, but are inserted properly into my note:
![image](https://user-images.githubusercontent.com/44440399/237017330-3453103f-bb3f-4d8c-bc70-8d8ceb509186.png)

**Comment by micahke** [comment]
@rizerphe thanks for the submitting this. I've seen it and a fix should be pushed soon

**Comment by micahke** [comment]
Fixed here: https://github.com/micahke/obsidian-gpt3-notes/commit/781d414485ee936ef7630b023c39126672724d1c
