### ISSUE TITLE
FR: include current note or selected text in prompt

### ISSUE THREAD

**Issue by etiennepellegrini** [micahke/obsidian-gpt3-notes#2]
Title says it all: it would be cool to be able to use the current note (or only parts of it, or only selected text, etc) as an input to GPT-3. 
This would allow using GPT-3 to summarize a note, or to re-organize it, or rewrite it ("make it sound more literary"), or write a poem about its subject!

Using selected text hopefully should be straight forward (in fact it's quite easy right now, just requires copying it before opening the plugin's modal). 
Using full notes might require stripping them of their metadata (and maybe other markdown stuff) depending on how chatGPT handles that...

**Comment by micahke** [comment]
Thats a really great idea actually. Will start working on that when I have some time but feel free to submit a PR if you'd like!

**Comment by micahke** [comment]
This was added [here](https://github.com/micahke/obsidian-gpt3-notes/pull/5) by @gmq
