### ISSUE TITLE
Feature requests - edit/add/delete prefix and postfix / enable copy from result window

### ISSUE THREAD

**Issue by HanumanTFM** [micahke/obsidian-gpt3-notes#4]
It would be very useful to have the ability to edit, add, and delete the prefix and postfix fields in order to customize the gpt3 queries to meet individual needs. This would allow users to tailor their queries to their most common questions, making it an easier and more efficient workflow.

also
It would be very useful to have the ability to select and copy text from the results window, as there may be times when only a portion of the result is relevant.

thank you

**Comment by mattjoyce** [comment]
I think this is a great idea, and perhaps a good way to do this is to have the prefixes as files in an Obsidian folder.

**Comment by micahke** [comment]
@HanumanTFM This is a great idea. I already implemented the text selection and editing feature your suggested. Let me know what you think. 

Custom prefixes, postfixes, and tokens are coming to the tool soon.

**Comment by micahke** [comment]
Check out this PR: https://github.com/micahke/obsidian-gpt3-notes/pull/8

**Comment by HanumanTFM** [comment]
That's great! Thank you for all you do!
