### ISSUE TITLE
Ubuntu 20.04 deb install DRM_IOCTL_I915_GEM_CONTEXT_DESTROY failed: Bad file descriptor

### ISSUE THREAD

**Issue by StohanzlMart** [micahke/obsidian-gpt3-notes#7]
Hello and thank you for implementing this great idea of merging them.

On Ubuntu 20.04 I get this toast: "There was an error: Please check your token or try again."

Terminal shows this:
```
$ obsidian 
2023-01-14 22:43:42 Loading main app package /opt/Obsidian/resources/obsidian.asar
2023-01-14 22:43:42 Checking for update using Github
2023-01-14 22:43:42 Success.
2023-01-14 22:43:42 Latest version is 1.1.9
2023-01-14 22:43:42 App is up to date.
Opening URL: https://beta.openai.com/account/api-keys
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
DRM_IOCTL_I915_GEM_CONTEXT_DESTROY failed: Bad file descriptor

```

**Comment by micahke** [comment]
@StohanzlMart this seems to be a problem with the OpenAI API. I was also getting this issue but not in a reproducible manner. Is this still occurring on your s system?

**Comment by StohanzlMart** [comment]
@micahke haha, yes works now. Just needed to pay for GPT3 API access. You plan to support ChatGPT API too?

**Comment by micahke** [comment]
@StohanzlMart yep i'll start integrating it as soon as it becomes officially available
