### ISSUE TITLE
GPT-3 rate limit error: please try again soon

### ISSUE THREAD

**Issue by davidadarme** [micahke/obsidian-gpt3-notes#9]
I just installed it and I try to test it but when generating the output it doesn't occur

![Screenshot_20230125-234058_Obsidian.jpg](https://user-images.githubusercontent.com/114038362/214760511-b1c3ad01-dd9d-42ca-8a70-cb0a2cf8cc9e.jpg)

Maybe it's because it's mobile? I'm a noob can you give me an explained solution?

**Comment by jlpython65** [comment]
Getting the same error

**Comment by micahke** [comment]
Yeah I've had this occasionally while testing as well. Seems to be happening on OpenAI's side so I'm guessing it has to do with server load.

**Comment by micahke** [comment]
OpenAI limits the amount of tokens you use per hour on the free tier. When you use these tokens up, they take an hour or so to refresh.
